config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'contacts#index'

  get 'home/index'

  resources :contacts
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :phones
  mount_uploader :avatar, AvatarUploader
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] || session[:locale] || I18n.default_locale
    I18n.locale = session[:locale]
  end

  load_and_authorize_resource unless: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.paginate(page: params[:page], per_page: 1)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :birthday, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-warning"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :birthday %>
    <%= f.input :avatar, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>
  <%= t('editing', name: t('contact.title', count: 1)) %>
</h1>

<%= render 'form' %>

<%= link_to t('show'), @contact, class: 'btn btn-info', role: :button %>
<%= link_to t('index'), contacts_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/contacts/index.html.erb
<h1>
  <%= t('listing', name: t('contact.title', count: 1)) %>
</h1>

<table class="table table-striped table-hover table-sm">
  <thead>
    <tr>
      <th scope="col">
        <%= t('contact.name') %>
      </th>
      <th scope="col">
        <%= t('contact.birthday') %>
      </th>
      <th scope="col">
        <%= t('actions') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td>
          <%= contact.name %>
        </td>
        <td>
          <%= l contact.birthday, format: :long %>
        </td>
        <td>
          <div class="btn-group btn-group-sm" role="group">
            <%= link_to t('show'), contact, class: 'btn btn-info', role: :button %>
            <%= link_to t('edit'), edit_contact_path(contact), class: 'btn btn-success', role: :button %>
            <%= link_to t('destroy'), contact, method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-danger', role: :button %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to t('new', name: t('contact.title', count: 1)), new_contact_path, class: 'btn btn-primary', role: :button %>

app/views/contacts/new.html.erb
<h1>
  <%= t('new', name: t('contact.title', count: 1)) %>
</h1>

<%= render 'form' %>

<%= link_to t('index'), contacts_path, class: 'btn btn-outline-secondary', role: :button %>

app/views/contacts/show.html.erb
<h1>
  <%= t('show', name: t('contact.title', count: 1)) %>
</h1>

<div class="card">
  <%= image_tag(@contact.avatar_url, class: 'card-img-top') if @contact.avatar? %>

  <div class="card-body">
    <h5 class="card-title">
      <%= @contact.name %>
    </h5>
    <p>
      <%= @contact.birthday %>
    </p>

    <%= link_to t('edit'), edit_contact_path(@contact), class: 'btn btn-primary', role: :button %>
    <%= link_to t('index'), contacts_path, class: 'btn btn-outline-secondary', role: :button %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Pós Guairacá
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to t('contacts'), root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse">
      <div class="navbar-nav">
        <%= link_to 'Any link', '#', class: 'nav-item nav-link' %>
      </div>

      <%= link_to 'pt-BR', root_path(locale: 'pt-BR'), class: 'nav-item nav-link' %>
      <%= link_to 'en', root_path(locale: 'en'), class: 'nav-item nav-link' %>

      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-item nav-link') %>
      <% end %>
    </div>
  </nav>

  <main class="container" role="main">
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
        <%= value %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
  </main>

</body>
</html>